# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20161204_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.RenameModel(
            old_name='UserStatistics',
            new_name='Statistics',
        ),
    ]
