# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
