# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20161204_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answer',
        ),
    ]
