# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_task_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='question',
        ),
    ]
